apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v-core.fullname" . }}
  labels:
    {{- include "v-core.labels" . | nindent 4 }}
data:
  DEPLOYMENT_ENVIRONMENT: {{ .Values.config.deploymentEnvironment | quote }}
  OTEL_EXPORTER_ENABLED: {{ .Values.config.otelExporterEnabled | quote }}
  OTEL_TRACES_SAMPLER_PROBABILITY: {{ .Values.config.otelTracesSamplerProbability | quote }}

